spring.datasource.url=jdbc:mysql://thomas.proxy.rlwy.net:11840/railway
spring.datasource.username=root
spring.datasource.password=HygbjkRhXGYGqQtvYqjQlrNIkhLtgKFX
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}